apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: security
data:
  falco.yaml: |
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/custom-rules.yaml

    log_level: info
    log_syslog: false

    json_output: true
    json_include_output_prop: true

    metrics:
      enabled: true
      interval: 15s
      
    syscall_event_drops:
      actions:
        - log
        - alert