apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: security
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      serviceAccountName: falco
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: custom-rules
          mountPath: /etc/falco/custom-rules.yaml
          subPath: custom-rules.yaml
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: custom-rules
        configMap:
          name: falco-rules